Update Dockerfiles
ppc64le-cloud/docker-ce-build pull request #165
Opened 2023-10-17 05:29 UTC by AshwinHIBM

Update the Docker build and test Dockerfiles with the latest versions of various packages including Docker-in-Docker.

2023-11-09 15:55 UTC, clnperez requested changes
This is a lot of great improvements. I'm thinking it could be more parameterized, so that any time it needs a change in image or docker version, those are things we could pass in vs a PR. If we don't have the CI set up for that yet, we can discuss do that in two phases.

2023-11-09 15:55 UTC, clnperez commented on images/docker-in-docker/Dockerfile
> +ENV CONTAINERD_VERSION=1.6.21-1
Is there a reason for removing the ARGs in this file?

2023-11-09 15:55 UTC, clnperez commented on test-repo-RPMS/Dockerfile
can you combine all these `RUN` lines into one, and then remove the yum cache (still all one RUN) to keep the image size small?

2023-11-09 15:55 UTC, clnperez commented on test-repo-RPMS/Dockerfile
> +ENV DOCKERD_COMMIT a3ca225e9c0e568cf87a7b60c951b939c3964c91
could these be made `ARG`s?

2023-11-10 11:28 UTC, AshwinHIBM commented on images/docker-in-docker/Dockerfile
> +ENV CONTAINERD_VERSION=1.6.21-1
As discussed, `ARG` isn't rendering correctly when pushed to _quay_ and hence we decided to stick with using `ENV` until we debug.

2023-11-10 12:56 UTC, AshwinHIBM commented on test-repo-RPMS/Dockerfile
Addressed in the latest update and tested locally. Pending staging and release tests.

2023-11-20 09:42 UTC, AshwinHIBM commented on test-repo-RPMS/Dockerfile
Tested on staging and release.

2023-12-11 14:26 UTC, clnperez requested changes
a few places where i think we can shrink image sizes

2023-12-11 14:26 UTC, clnperez commented on test-RPMS/Dockerfile
> +RUN yum install -y dnf-plugins-core || :
can you combine all these yum commands into one line and clear the cache to make this image smaller

2023-12-11 14:26 UTC, clnperez commented on test-repo-DEBS/Dockerfile
>  RUN apt-get update && apt-get install -y --no-install-recommends \
can these apt-get lines be combined? i do remember the tzdata one being tricky for me once, but maybe if you put them into different commands but the same `RUN` it will work

2023-12-11 14:26 UTC, clnperez commented on test-repo-RPMS/Dockerfile
> +RUN yum config-manager --set-enabled crb || :
same question here

2023-12-12 14:54 UTC, AshwinHIBM commented on test-RPMS/Dockerfile
> +RUN yum install -y dnf-plugins-core || :
Addressed

2023-12-13 12:49 UTC, AshwinHIBM commented on test-RPMS/Dockerfile
> +RUN yum install -y dnf-plugins-core || :
Addressed. Also converted `tini` version to ARG instead of ENV.

2023-12-13 12:50 UTC, AshwinHIBM commented on test-repo-RPMS/Dockerfile
> +RUN yum config-manager --set-enabled crb || :
Addressed

2023-12-13 12:53 UTC, AshwinHIBM commented on test-repo-DEBS/Dockerfile
>  RUN apt-get update && apt-get install -y --no-install-recommends \
The same `RUN` worked.

2023-12-14 18:54 UTC, clnperez approved these changes
LGTM

2023-12-15 09:26 UTC, merged