Upstream CI scripts
ppc64le-cloud/docker-ce-build pull request #176
Opened 2024-02-08 09:27 UTC by AshwinHIBM

Scripts to run tests on upstream moby repository
1. Check kernel configuration
2. Build dev image
3. Unit tests
4. Integration tests

2024-02-09 16:48 UTC, clnperez requested changes
i'm wondering if there is less we can embed as far as scripts, but overall this looks good. if you could just answer the one question i asked i'll let you know if i think this is okay to merge (after the little readme update)

2024-02-09 16:48 UTC, clnperez commented on README.md
> +5. periodic-config-docker
Can you make a new paragraph here and introduce these new jobs? The first are for building and testing docker-ce packages. And the new ones are for running the upstream CI tests. I'd just like for it to be clear that they're not related to the first 4.

2024-02-09 16:48 UTC, clnperez commented on upstream-master-ci/integration-tests.sh
> +exit 0
can you point me to where this docker run command came from?

2024-02-12 05:48 UTC, AshwinHIBM commented on upstream-master-ci/integration-tests.sh
> +exit 0
https://github.com/moby/moby/commit/59aa3dce8a3abc9d6eb29df7c76b4484e8758234#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8L312

2024-02-12 10:16 UTC, AshwinHIBM commented on README.md
> +5. periodic-config-docker
Modified: https://github.com/ppc64le-cloud/docker-ce-build/pull/176/commits/b09644d1e41d75057ea11b4c5afa574bbb03d351

2024-02-14 06:34 UTC, merged