Store CI logs
ppc64le-cloud/docker-ce-build pull request #206
Opened 2024-06-12 12:07 UTC by AshwinHIBM

Store logs generated by all the CI jobs by date.

2024-06-28 19:25 UTC, clnperez requested changes
a couple of suggestions for error messages

2024-06-28 19:25 UTC, clnperez commented on upstream-master-ci/build-dev-image.sh
> +      exit 1
shouldn't we log a message here that the mkdir failed? `could not create $1. exiting` etc?

2024-06-28 19:25 UTC, clnperez commented on upstream-master-ci/get-env-ci.sh
> +    s3fs ${COS_BUCKET_PRIVATE} ${PATH_COS}/s3_${COS_BUCKET_PRIVATE} -o url=${URL_COS_PRIVATE} -o passwd_file=${PATH_PASSWORD} -o ibm_iam_auth
same thought here about logging a potential failure. iirc there was a problem for a little bit where your mount command was failing

2024-06-28 19:25 UTC, clnperez commented on upstream-master-ci/info.sh
> +      exit 1
same here

2024-07-02 10:58 UTC, AshwinHIBM commented on upstream-master-ci/build-dev-image.sh
> +      exit 1
Addressed. I hope by _log_ you mean `echo` because this function `checkDirectory` is being used to create the logging directory and if we can't create it, there's nowhere we can write to.

2024-07-02 10:59 UTC, AshwinHIBM commented on upstream-master-ci/info.sh
> +      exit 1
Addressed with the only caveat mentioned here: https://github.com/ppc64le-cloud/docker-ce-build/pull/206#discussion_r1662314222

2024-07-09 16:20 UTC, merged